# permissions for end users to edit gowebs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goweb-editor-role
rules:
- apiGroups:
  - example.com
  resources:
  - gowebs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - gowebs/status
  verbs:
  - get
